### ISSUE TITLE
Use polling for dev target

### ISSUE THREAD

**Issue by pwalker** [flolu/nextjs-bazel#4]
Hey @flolu, I've used your repo as an example to get Next.js working with Bazel.  I've upgrade to Next.js 12.1.0, and I was able to remove the patching you've done.  The one part I couldn'1 get working was the ibazel command for the dev server.  As it turns out, I don't think the [package next.js uses to watch the filesystem](https://github.com/webpack/watchpack) will pick up the changes and do the fast-refreshing.  I had to see the `WATCHPACK_POLLING` env variable to get it to poll, and that made it work.

```
next(
    name = "dev",
    args = [
        "dev",

        # Root of app is the directory in which this BUILD.bazel file is located in
        package_name(),

        # To prevent webpack from bundling multiple react versions
        "--node_options=--preserve-symlinks-main",
        "--bazel_run_from_execroot",
    ],
    data = ["copy_source_files"] + _RUNTIME_DEPS,
    env = {
        "NODE_ENV": "development",
        "PORT": "3001",
        "WATCHPACK_POLLING": "1000"
    },
    tags = ["ibazel_notify_changes"],
)
```

I don't know if you'll find this useful, but I thought I'd drop a note here in the repo just in case, and help future googling.

**Comment by flolu** [comment]
We've stopped trying to combine Next.js + Bazel for now. But this is great to see anyways. Thank you @pwalker!
Maybe [this](https://github.com/bazelbuild/rules_nodejs/pull/3297) pull request will soon provide a flagship example for Next.js + Bazel.
